.TH msec 8 "17 Appr 2000" "Mandriva" "Mandriva Linux"
.IX msec
.SH NOME
msec \- tools di sicurezza Mandriva Linux
.SH SINTASSI
.B msec
[0-5 | custom]
.SH DESCRIZIONE
\fPmsec\fP è lo script principale del pacchetto msec. Esso permette all'amministratore di cambiare il livello di sicurezza del proprio sistema.
msec viene fornito con sei livelli di sicurezza preconfigurati. Questi livelli spaziano da poca sicurezza e facilità d'uso, a configurazione paranoica, adatta per applicazioni server molto delicate, gestite da esperti.
.PP
Devi esere root per eseguire \fPmsec\fP .
.br
Lancia "msec x" per impostare il livello di sicurezza a x (x=[0-5]). Esso modificherà il tuo sistema secondo le caratteristiche del livello di sicurezza x.
.br
Per un'accurata descrizione di ogni livello di sicurezza, consulta la documentazione in /usr/doc/msec-*/.
.PP
Se desideri creare il tuo livello di sicurezza, regolando finemente tutti i parametri disponibili, lancia "msec custom". Esso ti porrà delle domande su ogni caratteristica che vorrai abilitare prima di applicarla al sistema.
.SH FILE
/usr/sbin/msec
.br
L'eseguibile \fPmsec\fP (script sh)
.PP
/etc/security/msec/security.conf
.br
Contiene la configurazione del livello di sicurezza attualmente attivo.

.SH AUTORE
Vandoorselaere Yoann, Mandriva
.br
yoann@Mandriva.com

.SH TRADUTTORE
Salvatore Di Pietro
salvuz@despammed.com








