.TH init.sh 8 "15 Dec 1999" "Mandriva" "Mandriva Linux"
.IX msec
.SH NOM
msec \- Outils de sécurité Mandriva Linux
.SH SYNOPSIS
.B init.sh
[0-5 | custom]
.SH DESCRIPTION
\fPinit.sh\fP est le script principal du paquetage msec. Il permet à l'administrateur système de changer le niveau de sécurité de ce système.
msec est fourni avec six niveaux de sécurité déjà configurés. Ces niveaux s'échelonnent d'une sécurité minimale favorisant la facilité d'utilisation, à la configuration paranoïaque convenant aux applications sensibles des serveurs administrés par des experts.
.PP
Vous devez être super-utilisateur (root) pour lancer \fPinit.sh\fP .
.br
Lancer "init.sh x" pour obtenir le niveau de sécurité x (x=[0-5]). Cela modifiera votre système vers les caractéristiques du niveau de sécurité x.
.br
Pour une description précise de chaque niveau de sécurité, consulter la documentation dans /usr/doc/msec-*/.
.PP
Si vous souhaitez définir votre propre niveau de sécurité, en définissant précisément tous les paramètres, lancer "init.sh custom". Il vous sera alors demander de choisir les caractéristiques à activer, qui seront ensuite appliquées au système.
.SH FICHIERS
/etc/security/msec/init.sh
.br
L'exécutable \fPinit.sh\fP (script sh)
.PP
/etc/security/msec/security.conf
.br
Contient la configuration du niveau de sécurité actuel.

.SH AUTEUR
Vandoorselaere Yoann, Mandriva
