PACKAGE = msec
VERSION := $(shell grep 'Version:' $(PACKAGE).spec| cut -f 2)
RELEASE := $(shell grep 'Release:' $(PACKAGE).spec| cut -f 2)
TAG := $(shell echo "V$(VERSION)_$(RELEASE)" | tr -- '-.' '__')

all: promisc_check msec_find python

clean:
	-find . -name '*.o' -o -name '*.py[oc]' -o -name '*~' | xargs rm -f
	rm -f src/promisc_check/promisc_check
	rm -f src/msec_find/msec_find
	rm -f *.bz2

promisc_check: 
	(cd src/promisc_check && make)

msec_find:
	(cd src/msec_find && make)

python:
	-cd share; ./msec.py -h

install:
	mkdir -p $RPM_BUILD_ROOT/etc/security/msec
	mkdir -p $RPM_BUILD_ROOT/usr/share/msec
	mkdir -p $RPM_BUILD_ROOT/usr/sbin
	cp init-sh/*.sh $RPM_BUILD_ROOT/usr/share/msec
	cp cron-sh/*.sh $RPM_BUILD_ROOT/usr/share/msec
	cp init-sh/msec $RPM_BUILD_ROOT/usr/sbin
	cp conf/perm.* conf/server.* $RPM_BUILD_ROOT/etc/security/msec

	mkdir -p $RPM_BUILD_ROOT/var/log
	mkdir -p $RPM_BUILD_ROOT/var/log/security
	touch $RPM_BUILD_ROOT/etc/security/msec/security.conf
	touch $RPM_BUILD_ROOT/var/log/security.log
	cd src/promisc_check && make install
	cd src/msec_find && make install
	mkdir -p $RPM_BUILD_ROOT/usr/share/man/man8/
	install -d $(RPM_BUILD_ROOT)/usr/share/man/man8/
	install -m644 man/C/*8 $(RPM_BUILD_ROOT)/usr/share/man/man8/
	for i in man/??* ; do \
	    install -d $(RPM_BUILD_ROOT)/usr/share/man/`basename $$i`/man8 ; \
	    install -m 644 $$i/*.8 $(RPM_BUILD_ROOT)/usr/share/man/`basename $$i`/man8 ; \
	done	

version:
	@echo $(VERSION)-$(RELEASE)

# rules to build a test rpm

localrpm: clean localdist buildrpm

localdist: cleandist dir localcopy tar

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.bz2

dir:
	mkdir $(PACKAGE)-$(VERSION)

localcopy: clean
	find . -not -name "$(PACKAGE)-$(VERSION)" -a -not -name '*.bz2'|cpio -pd $(PACKAGE)-$(VERSION)/
	find $(PACKAGE)-$(VERSION) -type d -name CVS|xargs rm -rf 

tar:
	tar cvf $(PACKAGE)-$(VERSION).tar $(PACKAGE)-$(VERSION)
	bzip2 -9vf $(PACKAGE)-$(VERSION).tar
	rm -rf $(PACKAGE)-$(VERSION)

buildrpm:
	rpm -ta $(PACKAGE)-$(VERSION).tar.bz2

# rules to build a distributable rpm

rpm: changelog cvstag dist buildrpm

dist: cleandist dir export tar

export:
	cvs export -d $(PACKAGE)-$(VERSION) -r $(TAG) $(PACKAGE)

cvstag:
	cvs commit
	cvs tag $(CVSTAGOPT) $(TAG)

changelog: ../common/username
	cvs2cl -U ../common/username -I ChangeLog 
	rm -f ChangeLog.bak
	cvs commit -m "Generated by cvs2cl the `date '+%d_%b'`" ChangeLog
