PACKAGE = msec
VERSION = 0.60.3
SVNPATH = svn+ssh://svn.mandriva.com/svn/soft/msec

all: version promisc_check msec_find python
	make -C cron-sh

version:
	echo "version='$(VERSION)'" > src/msec/version.py

clean:
	-find . -name '*.o' -o -name '*.py[oc]' -o -name '*~' | xargs rm -f
	rm -f src/promisc_check/promisc_check
	rm -f src/msec_find/msec_find
	rm -f *.bz2
	make -C src/msec clean

promisc_check: 
	make -C src/promisc_check

msec_find:
	make -C src/msec_find

python:
	make -C src/msec

install: all
	mkdir -p $(RPM_BUILD_ROOT)/etc/security/msec
	mkdir -p $(RPM_BUILD_ROOT)/usr/share/msec
	mkdir -p $(RPM_BUILD_ROOT)/usr/sbin
	cp init-sh/*.sh $(RPM_BUILD_ROOT)/usr/share/msec
	cp cron-sh/*.sh $(RPM_BUILD_ROOT)/usr/share/msec
	# install main msec files
	for i in libmsec.py config.py msec.py msecperms.py msecgui.py help.py version.py; do \
	    install -m755 src/msec/$$i $(RPM_BUILD_ROOT)/usr/share/msec ; \
	done
	for i in msec msecperms msecgui; do \
		install -m755 src/msec/$$i $(RPM_BUILD_ROOT)/usr/sbin ; \
	done
	cp conf/perm.* conf/server.* conf/level.* $(RPM_BUILD_ROOT)/etc/security/msec

	mkdir -p $(RPM_BUILD_ROOT)/var/log
	mkdir -p $(RPM_BUILD_ROOT)/var/log/security
	touch $(RPM_BUILD_ROOT)/var/log/security.log
	touch $(RPM_BUILD_ROOT)/var/log/msec.log
	cd src/promisc_check && make install
	cd src/msec_find && make install
	mkdir -p $(RPM_BUILD_ROOT)/usr/share/man/man8/
	install -d $(RPM_BUILD_ROOT)/usr/share/man/man8/
	install -m644 man/C/*8 $(RPM_BUILD_ROOT)/usr/share/man/man8/
	for i in man/??* ; do \
	    install -d $(RPM_BUILD_ROOT)/usr/share/man/`basename $$i`/man8 ; \
	    install -m 644 $$i/*.8 $(RPM_BUILD_ROOT)/usr/share/man/`basename $$i`/man8 ; \
	done	

	# profile.d config
	mkdir -p $(RPM_BUILD_ROOT)/etc/profile.d/
	install -m755 profile.d/msec.sh $(RPM_BUILD_ROOT)/etc/profile.d/
	install -m755 profile.d/msec.csh $(RPM_BUILD_ROOT)/etc/profile.d/

	# logrotate
	mkdir -p $(RPM_BUILD_ROOT)/etc/logrotate.d
	install -m644 msec.logrotate $(RPM_BUILD_ROOT)/etc/logrotate.d/msec

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.bz2

tar:
	tar cfj $(PACKAGE)-$(VERSION).tar.bz2 $(PACKAGE)-$(VERSION)
	rm -rf $(PACKAGE)-$(VERSION)

dist: cleandist export tar

changelog: 
	svn up
	svn2cl --accum --authors=../common/username.xml -o ChangeLog || : 
	svn commit -m "Generated by svn2cl the `LC_TIME=C date '+%d_%b'`" ChangeLog
	rm -f ChangeLog.bak

export:
	rm -fr $(PACKAGE)-$(VERSION)
	svn export -q -rBASE . $(PACKAGE)-$(VERSION)

svntag:
	svn cp -m 'version $(VERSION)' $(SVNPATH)/trunk $(SVNPATH)/tags/v$(VERSION)
