#!/bin/bash

if [[ -z $1 ]]; then
	echo "Usage : $0 [0-5]"
	echo "Usage : $0 \"custom\""
	exit 1
fi


if [[ ${1} == custom ]]; then
	/usr/share/msec/custom.sh
	exit 0;
fi

if [[ -f /usr/share/msec/level$1.sh ]]; then
	/usr/share/msec/level$1.sh
	if [[ -f /usr/share/msec/perm.$1 ]]; then
		/usr/share/msec/file_perm.sh /usr/share/msec/perm.$1
	else
		echo "Couldn't find the default permissions for level $1."
	fi
else
    echo "Security level $1 not availlable..."
fi

