.TH msec 8 "29 Sep 2001" "Mandriva" "Mandriva Linux"
.IX msec
.SH NAZWA
msec \- Narzędzia bezpieczeństwa Mandriva Linux
.SH SKŁADNIA
.B msec
([-o <option>=<value>...]) ([0-5])
.SH OPIS
\fPmsec\fP jest głównym skryptem pakietu msec. Umożliwia on
administratorowi systemu zmianę poziomu bezpieczeństwa dla systemu.
msec jest dostarczony z sześcioma wstępnie skonfigurowanymi poziomami
bezpieczeństwa. Od najsłabszego bezpieczeństwa, łatwego w użyciu do
paranoidalnej konfiguracji odpowiedniej dla bardzo wrażliwych
aplikacji serwerowych.
.PP
Skrypt \fPmsec\fP można uruchamiać tylko z poziomu administratora.
.br
Uruchom "msec x" aby ustawić poziom bezpieczeństwa na x (x=[0-5]).
Wywołanie to zmodyfikuje system w zależności od funkcji poziomu
bezpieczeństwa. Skrypt wywoływany bez argumentów wymusi bieżący
poziom bezpieczeństwa bez jego zmiejszania.
.br
Wszystkie zmiany są zapisywane do dziennika systemowego z funkcją
AUTH przy wywołaniu nie interaktywnym (na przykład za pośrednictwem
mechanizmu cron) lub z funkcją LOCAL1 przy wywoływaniu interaktywnym
(z wiersza poleceń lub na przykład z Centrum Sterowania Mandriva Linux).
.br
Aby uzyskać pełny opis każdego poziomu bezpieczeństwa, skonsultuj
się z dokumentacją w pliku /usr/share/doc/msec-*/security.txt.
.PP
Jeśli chcesz uczynić zmiany w bieżącym poziomie bezpieczeństwa,
użyj pliku /etc/security/msec/perm.local aby nadpisać 
uprawnienia/właścicieli/grupy oraz /etc/security/msec/level.local
aby nadpisać zasady (zajrzyj do manuala mseclib(3) aby uzyskać
więcej szczegółów).
.PP
Dostępne opcje:
.TP
\fB\-o all-local-files=<wartość>\fR
jeśli <wartość> wynosi 1, zakłada się, że wszystkie pliki są lokalne.
.TP
\fB\-o log=<wartość>\fR
jeśli <wartość> jest różna niż syslog komunikaty nie są wysyłane do
dziennika tylko na wyjście standardowe
.TP
\fB\-o nolocal=<ścieżka>\fR
bez wczytywania zasad /etc/security/msec/level.local.
.TP
\fB\-o non-local-fstypes=<wartość>\fR
<wartość> jest listą nielokalnych systemowych typów plików rozdzielonych
spacjami.
.TP
\fB\-o print=<wartość>\fR
jeśli <wartość> jest równa 1, wypisuje domyślne wartości zasad.
.TP
\fB\-o root=<ścieżka>\fR
używanie parametru <ścieżka> jako głównego systemu plików. 
.SH PLIKI
/usr/sbin/msec
.br
Wykonywalny plik \fPmsec\fP (skrypt sh)
.PP
/var/lib/msec/security.conf
.br
Zawiera konfigurację bieżącego aktywnego poziomu bezpieczeństwa. Te
ustawienia mogą być nadpisane w pliku /etc/security/msec/security.conf.

.SH AUTORZY
Vandoorselaere Yoann, Mandriva

.SH TŁUMACZENIE
Arkadiusz Lipiec <alipiec@elka.pw.edu.pl>
