.TH grpuser "16 Dec 1999" "Mandrakesoft" "Linux-Mandrake"
.IX grpuser
.SH NAME
grpuser \- Adds/Removes users into groups
.SH SYNOPSIS
.B grpuser --add [ groupname ] [ username ]
.br
.B grpuser --del [ groupname ] [ username ] 
.SH DESCRIPTION
\fPgrpuser\fP helps the system administrator in maintaining group lists. It enables him to add/ remove users from a group in an easy way.
.br
\fPgrpuser\fP has to be run in one of two ways:
.PP
grpuser --add [ groupname ] [ username ]
.br
Adds the user username to group groupname.
.PP
grpuser --del [ groupname ] [ username ] 
.br
Removes the user username from group groupname.
.SH FILES
/etc/passwd
.br
Users list.
.PP
/etc/group
.br
Groups list and users owned by these groups.

.SH AUTHOR
Vandoorselaere Yoann, Thanks to Francis Galiegue, Mandrakesoft.
.br
yoann@mandrakesoft.com