.TH msec 8 "17 апреля 2000" "Mandrakesoft" "Mandrakelinux"
.IX msec
.SH НАЗВАНИЕ
msec \- инструментальное средство безопасности Mandrake
.SH СИТАКСИС
.B msec 
[0-5 | custom]
.SH ОПИСАНИЕ
\fPmsec\fP является главным скриптом из пакета msec. Он дает возможность
администратору изменять уровни безопасности системы.
Msec оснащен шестью предварительно настроенными уровнями безопасности. Эти
уровни, начиная от низкой безопасности и до параноидальной настройки, применимы
к очень чувствительным серверным приложениям, управляемых экспертами.
.PP
Вы должны иметь права root'a для запуска \fPmsec\fP.
.br
Выполните "msec n", чтобы установить n-ый уровень безопасность (n=[0-5]).
Это изменит вашу систему согласно параметрам n-го уровня безопасности.
.br
Чтобы подробно ознакомиться с каждым уровнем безопасности, прочтите
Документацию из /usr/doc/msec-*/.
.PP
Если вы желаете установить ваш собственный уровень безопасности, тонко
настроить все доступные параметры, выполните "msec custom". Он будет
запрашивать у вас подтверждения на включение каждого параметра, а затем
применит их к системе.
.SH ФАЙЛЫ
/usr/sbin/msec
.br
Исполняемый файл \fPmsec\fP (скрипт sh).
.PP
/etc/security/msec/security.conf
.br
Содержит настройки текущего активного уровня безопасности.

.SH АВТОР
Vandoorselaere Yoann, Mandrakesoft

.SH ПЕРЕВОД
Павел Марьянов
.br
acid_jack@ukr.net

