#!/usr/bin/python
#
# This script creates DrakSec help strings from libmsec code docstrings.
#

import sys
import imp
import inspect
import re

import config
from libmsec import MSEC
from msec import Log

header = '''package security::help;
# !! THIS FILE WAS AUTO-GENERATED BY draksec_help.py !!
# !! DO NOT MODIFY HERE, MODIFY IN THE *MSEC* CVS !!

use strict;
use common;

our %help = (
'''

footer = ''');
'''

### strings used in the rewritting
function_str = ''''%s' => N("%s"),
'''

# process all configuration parameters
log = Log(log_syslog=False, log_file=False)
msec = MSEC(log)

print header

for variable in config.SETTINGS:
    levels, callback = config.SETTINGS[variable]
    func = msec.get_action(callback)
    if func:
        print function_str % (variable, func.__doc__.strip())

print footer

# draksec_help.py ends here
