#!/bin/sh
#
# Wrapper for msecgui
#

if [ "`whoami`" != "root" ]; then
    echo 'msec: sorry, you must be root !'
    exit 1
fi

MSEC=/usr/share/msec/msecgui.py
OPT="$@"

exec $MSEC $OPT

# msec ends here
