.TH msec 8 "29 Srp 2001" "Mandriva" "Mandriva Linux"
.IX msec
.SH NÁZEV
msec \- Bezpeènostní nástroje spoleènosti Mandriva Linux
.SH SYNAPSE
.B msec ([-o <volba>=<hodnota>...]) ([0-5])
.SH POPIS
Skript \fPmsec\fP je hlavním skriptem balíèku msec. Umo¾òuje správci systému zmìnit úroveò bezpeènostního nastavení systému.
Aplikace msec je dodávána s ¹esti pøednastavenými bezpeènostními úrovnìmi. Tyto úrovnì jsou v rozsahu od velmi slabé úrovnì zabezpeèení a snadnìj¹ího zpùsobu pou¾ití a¾ po paranoidní nastavení, vhodné pro velmi citlivé aplikace na servery.
.PP
Abyste mohli skript \fPmsec\fP spustit, musíte být pøihlá¹eni jako u¾ivatel root.
.br
Spus»te skript "msec x", chcete-li nastavit úroveò bezpeènosti na úroveò x (x=[0-5]). Skript upraví vá¹ systém podle vlastností vybrané úrovnì x. Pokud zavoláte tento program bez parametrù, program automaticky znovu zavede aktuální úroveò bezpeènosti bez jejího sní¾ení.
.br
V¹echny zmìny jsou zaznamenávány do systémového logu pomocí nástroje AUTH, pokud je \fBmsec\fP volán neinteraktivnì (napøíklad démonem \fBcron\fP), nebo pomocí nástroje LOCAL1, pokud je \fBmsec\fP volán interaktivnì (napø. z pøíkazové øádky nebo z Ovládacího centra Mandriva Linux).
.br
Podrobnìj¹í popis ka¾dé z bezpeènostních úrovní naleznete v dokumentaci umístìné v souborech /usr/doc/msec-*/security.txt.
.PP
Chcete-li provést zmìny ve stávající úrovni bezpeènosti, pou¾ijte soubor /etc/security/msec/level.local a pøepi¹te práva/u¾ivatele/skupiny, nebo pou¾ijte soubor /etc/security/msec/level.local a pøepi¹te pravidla (viz mseclib(3) pro více detailù).
.SH "DOSTUPNÉ VOLBY"
.IP "\fB\-o all-local-files=<hodnota>"
pokud je nastaveno na 1, pova¾ují se v¹echny soubory za lokální.
.IP "\fB\-o log=<hodnota>"
pokud není zadaná hodnota syslog, nezaznamenávají se zmìny do systémového logu, ale na standardní výstup.
.IP "\fB\-o nolocal=<cesta>"
nenaètou se pravidla ze souboru /etc/security/msec/level.local.
.IP "\fB\-o non-local-fstypes=<hodnota>"
<hodnota> pøedstavuje seznam nelokálních souborových systémù oddìlený èárkami.
.IP "\fB\-o print=<hodnota>"
pokud je nastaveno na 1, vypí¹í se výchozí hodnoty pravidel.
.IP "\fB\-o root=<cesta>"
pou¾ije <cestu> jako koøen souborového systému.
.SH SOUBORY
/usr/sbin/msec
.br
Spustitelný soubor \fPmsec\fP (skript shellu sh)
.PP
/var/lib/msec/security.conf
.br
Obsahuje nastavení právì aktivní bezpeènostní úrovnì. Tato nastavení lze pøepsat v souboru /etc/security/msec/security.conf
.SH AUTOR
Vandoorselaere Yoann, Mandriva
