.TH msec 8 "17 Dub 2000" "Mandrakesoft" "Linux-Mandrake"
.IX msec
.SH NÁZEV
msec \- Bezpeènostní nástroje spoleènosti Mandrake
.SH SYNAPSE
.B msec
[0-5 | custom]
.SH POPIS
Skript \fPmsec\fP je hlavním skriptem balíèku msec. Umo¾òuje správci systému zmìnit úroveò bezpeènostního nastavení systému.
Aplikace msec je dodávána s ¹esti pøednastavenými bezpeènostními úrovnìmi. Tyto úrovnì jsou v rozsahu od velmi slabé úrovnì zabezpeèení a snadnìj¹ího zpùsobu pou¾ití a¾ po paranoidní nastavení, vhodné pro velmi citlivé aplikace na servery, spravované experty.
.PP
Abyste mohli skript \fPmsec\fP spustit, musíte být pøihlá¹eni jako u¾ivatel root.
.br
Spus»te skript "msec x", chcete-li nastavit úroveò bezpeènosti na úroveò x (x=[0-5]). Skript upraví vá¹ systém podle vlastností vybrané úrovnì x.
.br
Podrobnìj¹í popis ka¾dé z bezpeènostních úrovní naleznete v dokumentaci umístìné v souborech /usr/doc/msec-*/.
.PP
Chcete-li nastavit va¹i vlastní bezpeènostní úroveò, a podrobnì doladit ka¾dý z parametrù, spus»te pøíkaz "msec custom". Budete dotázáni na ka¾dou vlastnost, zda-li ji chcete povolit, a poté vybrané vlastnosti aplikuje na vá¹ systém.
.SH SOUBORY
/usr/sbin/msec
.br
Spustitelný soubor \fPmsec\fP (skript shellu sh)
.PP
/etc/security/msec/security.conf
.br
Obsahuje nastavení právì aktivní bezpeènostní úrovnì.

.SH AUTOR
Vandoorselaere Yoann, Mandrakesoft
.br
yoann@mandrakesoft.com









