.TH msec 8 "29 Sep 2001" "Mandriva" "Mandriva Linux"
.IX msec
.SH NIMI
msec \- Mandriva Linux turvallisuustyökalut
.SH YLEISKATSAUS
.B msec
([-o <optio>=<arvo>...]) ([0-5])
.SH KUVAUS
\fPmsec\fP on msec-paketin pääskripti. Se sallii järjestelmän ylläpitäjää muuttaa
järjestelmän turvatasoa. msec tarjoaa kuusi valmiiksi määritettyä turvatasoa,
jossa huono turvataso / helposti käytettävissä vastaa taso 0 ja vainoharhainen / 
vaikeampi käyttää taso 5. Näitä eri tasoja sopivat eri käyttötarkoituksiin, ja 
ovat vapaasti asiantuntijan valittavissa.
.PP
Sinun pitää olla 'root' suorittaaksesi \fPmsec\fP .
.br
Suorita "msec x" asettaaksesi turvatasoa (x=[0-5]). Se muokkaa järjestelmäsi 
vastaamaan taso x määrityksiä ja ominaisuuksia. Jos suoritat msec ilman
parametrejä, se ylläpitää nykyisen turvatason iman turvallisuuden alentamista.
.br
Kaikki muutokset kirjoitetaan järjestelmälokiin AUTH kautta kun sitä kutsutaan 
automaatisesti (esim. käyttäen cron) tai LOCAL1 kautta kun sitä kutsutaan
interaktiivisesti (esim. komentorivistä tai Mandriva Linuxn Ohjauskeskuksen kautta).
.br
Saadaaksesi tarkempi kuvaus eri turvatasosta, lue dokumentaatiota jota löydät
hakemistosta /usr/share/doc/msec-*/security.txt.
.PP
Jos haluat määrittää omaa turvatasoa, jossa voit vapaasti hienosäätää kaikki
parametrit, suorita "msec custom". Se kysyy sinulta jokaisesta ominaisuudesta
jos haluat ottaa sitä käyttöön vai ei. Sitten kun olet vastannut kaikkiin 
kysymyksiin se säätää järjestelmäsi määrittelysi mukaan.
.PP
Jos haluattehdä muutoksia nykyiselle tasolle, käytä
'/etc/security/msec/perm.local' ohittaaksesi oikeudet/omitajat/ryhmät ja
'/etc/security/msec/level.local' ohittaaksesi sääntöjä (katso mseclib(3) 
jos haluat tarkempia tietoja).
.PP
Käytettävissä olevia optioita:
.TP
\fB\-o all-local-files=<arvo>\fR
jos <arvo> on 1, huomioi että kaikki tiedostot ovat paikallisia.
.TP
\fB\-o log=<>\fR
jos <arvo> on eri kuin syslog, kirjoita järjestelmälokin sijasta
oletus virhelokiin, yleensä konsoliin.
.TP
\fB\-o nolocal=<hakemisto>\fR
älä lataa /etc/security/msec/level.local sääntöjä.
.TP
\fB\-o non-local-fstypes=<arvo>\fR
<arvo> on listaus ei-paikallisista tiedostojärjestelmä-tyypeistä 
pilkulla erotettuna.
.TP
\fB\-o print=<arvo>\fR
jos <arvo> on 1, tulosta sääntöjen oletusarvot.
.TP
\fB\-o root=<hakemisto>\fR
käytä <hakemisto> tiedostojärjestelmän päähakemistona
.SH TIEDOSTOT
/usr/sbin/msec
.br
\fPmsec\fP suoritettava ohjelma (sh skripti)
.PP
/var/lib/msec/security.conf
.br
Sisältää nykyisen käytössä olevan turvatason asetuksia. Näitä asetuksia
voit ohittaa tiedostossa /etc/security/msec/security.conf.
.SH TEKIJÄ
Vandoorselaere Yoann, Mandriva
