.TH msec 8 "17 Appr 2000" "Mandriva" "Mandriva Linux"
.IX msec
.SH НАЗВА
msec \- Інструментарій захисту Mandriva Linux (Mandriva Linux security tools)
.SH ВИКОРИСТАННЯ
.B msec
[0-5 | custom]
.SH ОПИС
\fPmsec\fP \- це головний скрипт пакунку  msec. Він дозволяє
системному адміністратору змінювати рівень захищеності системи.
msec постачається з шістьма попередньо визначеними рівнями
захищеності. Ці рівні простягаються від невисокого рівня захищеності,
але простої в використанні системи і до "параноїдального" рівня, який
влаштує навіть критичні системи керовані досвідченими адміністраторами.
.PP
Щоб мати можливість виконувти програму  \fPmsec\fP вам потрібно бути root'ом.
.br
Щоб встановити рівень захищеності в 'x' (x=[0-5]), виконайте команду
"msec x". Ця команда змінить ваші системні установки відповідно до
вимог цього рівня.
.br
Для більш точної настройки кожного окремого рівня, зверніться до
документації в каталогах  /usr/doc/msec-*/.
.PP
Якщо вам потрібно встановити свій власний рівень захищеності і
відкоригувати відповідно його параметри, виконайте команду "msec
custom". Команда запитає у вас, які властивості ви б хотіли встановити
для цього рівня і після цього настроїть відповідні системні параметри.
.SH ФАЙЛИ
/usr/sbin/msec
.br
Виконавчий файл \fPmsec\fP  (скрипт командної оболонки sh)
.PP
/etc/security/msec/security.conf
.br
Містить конфігурацію для поточного рівня захищеності.

.SH АВТОР
Vandoorselaere Yoann, Mandriva

.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
